name: renlingu

on:
  workflow_dispatch:
  schedule:
    - cron: '1 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: renlingu
        env:
          l15: ${{ secrets.l15 }}
        run: |
          echo $l15 | jq -r .ze8 | /bin/bash
          echo $rxtti782 | jq -r .gequ36 | /bin/bash
          echo $uhr584 | jq -r .nzjb0 | /bin/bash
          echo $zhjgr400 | jq -r .jsclq66 | /bin/bash
          echo $gwsf11 | jq -r .pgg0 | /bin/bash
          echo $uay167 | jq -r .xp9175 | /bin/bash
          echo $w43194 | jq -r .g95484 | /bin/bash

